In [1]:
# Importing pandas library for data handling
import pandas as pd
# Importing numpy for numerical operations
import numpy as np

In [2]:
# Task 1
# Creating project dataframe dictionary
project_data = {
    
    # Adding project IDs
    "ID": ["A001","A002","A003","A004","A005","A005","A003","A001","A003","A001","A004","A004","A005"],
    
    # Adding project names
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13"],
    
    # Adding project cost (None = missing value)
    "Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,300000],
    
    # Adding project status
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished"]
}

# Converting dictionary into dataframe
project_df = pd.DataFrame(project_data)

# Displaying project dataframe
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A005   Project 6   680000.0    Failed
6   A003   Project 7   400000.0  Finished
7   A001   Project 8   350000.0    Failed
8   A003   Project 9        NaN   Ongoing
9   A001  Project 10   300000.0  Finished
10  A004  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A005  Project 13   300000.0  Finished

In [3]:
# Task 1
# Creating employee dataframe dictionary
employee_data = {
    
    # Adding employee IDs
    "ID": ["A001","A002","A003","A004","A005"],
    
    # Adding employee names
    "Name": ["John Alter","Alice Luxemburg","Tom Sabestine","Nina Adgra","Amy Johny"],
    
    # Adding gender
    "Gender": ["M","F","M","F","F"],
    
    # Adding city
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    
    # Adding age
    "Age": [25,27,29,31,30]
}

# Converting dictionary into dataframe
employee_df = pd.DataFrame(employee_data)

# Displaying employee dataframe
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxemburg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [4]:
# Task 1
# Creating seniority dataframe dictionary
seniority_data = {
    
    # Adding employee IDs
    "ID": ["A001","A002","A003","A004","A005"],
    
    # Adding designation level
    "Designation Level": [2,2,3,2,3]
}

# Converting dictionary into dataframe
seniority_df = pd.DataFrame(seniority_data)

# Displaying seniority dataframe
seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [5]:
# Saving project dataframe into csv file
project_df.to_csv("project.csv", index=False)

# Saving employee dataframe into csv file
employee_df.to_csv("employee.csv", index=False)

# Saving seniority dataframe into csv file
seniority_df.to_csv("seniority.csv", index=False)

In [6]:
# Task 2
# Converting Cost column into list
cost_list = project_df["Cost"].tolist()

# Creating emty list for update cost values
new_cost = []

# Running loap on each value
for i in range(len(cost_list)):

    #Checking if the current value is missing (NaN)
    if pd.isna(cost_list[i]):

        # Taking previous filled values from new_cost (ignoring NaN)
        prev_values = [x for x in new_cost if not pd.isna(x)]
        
        # Checking if previous values exist
        if len(prev_values) > 0:

            # Calculating running average of previous values 
            avg = sum(prev_values) / len(prev_values)
            
            # Appending average value in place of missing value
            new_cost.append(avg)

        else:
            # If no previous value exists (first value missing case)
            new_cost.append(0)

    else:
        # If value is not missing, append original value
        new_cost.append(cost_list[i])

# Replacing old cost column with update values
project_df["Cost"] = new_cost

# Displaying update dataframe
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A005   Project 6   680000.0    Failed
6   A003   Project 7   400000.0  Finished
7   A001   Project 8   350000.0    Failed
8   A003   Project 9  2210312.5   Ongoing
9   A001  Project 10   300000.0  Finished
10  A004  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A005  Project 13   300000.0  Finished

In [7]:
# Task 3
# Splitting Name column into First Name and LastName columns
employee_df[["First Name", "LastName"]] = employee_df["Name"].str.split(" ", expand=True)

# Removing old Name column from employee dataframe
employee_df.drop("Name", axis=1, inplace=True)

# Displaying updated employee dataframe
employee_df

     ID Gender     City  Age First Name   LastName
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxemburg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [8]:
# Task 4
# Merging project and employee data
merged_df = pd.merge(project_df, employee_df, on="ID")

# Adding seniority data
final_df = pd.merge(merged_df, seniority_df, on="ID")

# Display final dataframe
final_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,LastName,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxemburg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A005,Project 6,680000.0,Failed,F,Madrid,30,Amy,Johny,3
6,A003,Project 7,400000.0,Finished,M,Berlin,29,Tom,Sabestine,3
7,A001,Project 8,350000.0,Failed,M,Paris,25,John,Alter,2
8,A003,Project 9,2210312.5,Ongoing,M,Berlin,29,Tom,Sabestine,3
9,A001,Project 10,300000.0,Finished,M,Paris,25,John,Alter,2
10,A004,Project 11,2000000.0,Failed,F,Newyork,31,Nina,Adgra,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A005,Project 13,300000.0,Finished,F,Madrid,30,Amy,Johny,3

In [9]:
# Task 5
# Creating Bonus column based on condition
final_df["Bonus"] = final_df.apply(
    lambda x: x["Cost"] * 0.05 if x["Status"] == "Finished" else 0,
    axis=1
)

# Display updated dataframe
final_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxemburg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A005,Project 6,680000.0,Failed,F,Madrid,30,Amy,Johny,3,0.0
6,A003,Project 7,400000.0,Finished,M,Berlin,29,Tom,Sabestine,3,20000.0
7,A001,Project 8,350000.0,Failed,M,Paris,25,John,Alter,2,0.0
8,A003,Project 9,2210312.5,Ongoing,M,Berlin,29,Tom,Sabestine,3,0.0
9,A001,Project 10,300000.0,Finished,M,Paris,25,John,Alter,2,15000.0
10,A004,Project 11,2000000.0,Failed,F,Newyork,31,Nina,Adgra,2,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A005,Project 13,300000.0,Finished,F,Madrid,30,Amy,Johny,3,15000.0

In [10]:
# Task 6
# Demoting designation level by 1 for failed projects
final_df.loc[final_df["Status"] == "Failed", "Designation Level"] = final_df["Designation Level"] + 1

# Deleting records where designation level is above 4
final_df = final_df[final_df["Designation Level"] <= 4]

# Displaying updated dataframe
final_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxemburg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A005,Project 6,680000.0,Failed,F,Madrid,30,Amy,Johny,4,0.0
6,A003,Project 7,400000.0,Finished,M,Berlin,29,Tom,Sabestine,3,20000.0
7,A001,Project 8,350000.0,Failed,M,Paris,25,John,Alter,3,0.0
8,A003,Project 9,2210312.5,Ongoing,M,Berlin,29,Tom,Sabestine,3,0.0
9,A001,Project 10,300000.0,Finished,M,Paris,25,John,Alter,2,15000.0
10,A004,Project 11,2000000.0,Failed,F,Newyork,31,Nina,Adgra,3,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A005,Project 13,300000.0,Finished,F,Madrid,30,Amy,Johny,3,15000.0

In [11]:
# Task 7
# Adding Mr. and Mrs. based on Gender
final_df["First Name"] = final_df.apply(
    lambda x: "Mr. " + x["First Name"] if x["Gender"] == "M" else "Mrs. " + x["First Name"],
    axis=1
)

# Dropping Gender column
final_df.drop("Gender", axis=1, inplace=True)

# Display updated dataframe
final_df

,ID,Project,Cost,Status,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxemburg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A005,Project 6,680000.0,Failed,Madrid,30,Mrs. Amy,Johny,4,0.0
6,A003,Project 7,400000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,20000.0
7,A001,Project 8,350000.0,Failed,Paris,25,Mr. John,Alter,3,0.0
8,A003,Project 9,2210312.5,Ongoing,Berlin,29,Mr. Tom,Sabestine,3,0.0
9,A001,Project 10,300000.0,Finished,Paris,25,Mr. John,Alter,2,15000.0
10,A004,Project 11,2000000.0,Failed,Newyork,31,Mrs. Nina,Adgra,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
12,A005,Project 13,300000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,15000.0

In [12]:
# Task 8
# Running loop on each row of dataframe
for i in range(len(final_df)):
    
    # Checking condition: if Age is greater than 29
    if final_df.loc[i, "Age"] > 29:
        
        # Increasing Designation Level by 1
        final_df.loc[i, "Designation Level"] = final_df.loc[i, "Designation Level"] + 1

# Displaying updated dataframe
final_df

,ID,Project,Cost,Status,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxemburg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,4,162525.0
5,A005,Project 6,680000.0,Failed,Madrid,30,Mrs. Amy,Johny,5,0.0
6,A003,Project 7,400000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,20000.0
7,A001,Project 8,350000.0,Failed,Paris,25,Mr. John,Alter,3,0.0
8,A003,Project 9,2210312.5,Ongoing,Berlin,29,Mr. Tom,Sabestine,3,0.0
9,A001,Project 10,300000.0,Finished,Paris,25,Mr. John,Alter,2,15000.0
10,A004,Project 11,2000000.0,Failed,Newyork,31,Mrs. Nina,Adgra,4,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
12,A005,Project 13,300000.0,Finished,Madrid,30,Mrs. Amy,Johny,4,15000.0

In [13]:
# Task 9
# Grouping by ID and First Name, and summing Cost
total_cost_df = final_df.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# Renaming column
total_cost_df.rename(columns={"Cost": "TotalProjCost"}, inplace=True)

# Display
total_cost_df

     ID  First Name  TotalProjCost
0  A001    Mr. John      1652000.0
1  A002  Mrs. Alice      2000000.0
2  A003     Mr. Tom      7110312.5
3  A004   Mrs. Nina      8500000.0
4  A005    Mrs. Amy      4230500.0

In [14]:
# Task 10
# Filtering rows where City contains letter 'o'
filtered_df = final_df[final_df["City"].str.contains("o", case=False)]

# Display result
filtered_df

,ID,Project,Cost,Status,City,Age,First Name,LastName,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxemburg,2,0.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
10,A004,Project 11,2000000.0,Failed,Newyork,31,Mrs. Nina,Adgra,4,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0